#!/bin/sh
# Simple and stupid build script.
# Should really be replaced by a Makefile soon.

echo Building Van Gogh code.
avr-gcc -mmcu=atmega1284p -xassembler-with-cpp \
        vangogh.S \
        vangogh_882_cgafont.S \
        vangogh_884_tilemap.S \
        -o vangogh.elf && \
avr-objcopy -j .text -j .data -O ihex vangogh.elf vangogh.hex

echo Done.
