#!/bin/sh
# Simple script for flashing the Van Gogh AVR with the target program.

# First line is for external clock drive, second is for external crystal
#avrdude -p m1284p -c avrisp2 -e -U lfuse:w:0xe0:m -U hfuse:w:0xd9:m -U efuse:w:0xff:m
#avrdude -p m1284p -c avrisp2 -e -U lfuse:w:0xbf:m -U hfuse:w:0xd9:m -U efuse:w:0xff:m
avrdude -p m1284p -c avrisp2 -e -U flash:w:vangogh.hex
