#!/bin/sh
# Simple script for flashing the AVR with the target program.

#avrdude -p m644 -c avrisp2 -e -U lfuse:w:0xe0:m -U hfuse:w:0xd9:m -U efuse:w:0xff:m
avrdude -p m644 -c avrisp2 -e -U flash:w:rosewater.hex
